import { Globe2 } from 'lucide-react';
import React from 'react';
import { 
  BarChart2, Package, Truck, AlertTriangle, Activity, 
  Brain, FileText, Settings, Database, Server, Link, 
  Map, Target, Zap, LayoutDashboard, Globe, Network, Users,
  Clock, History, Sliders, ShieldAlert, Eye, HelpCircle, GitBranch,
  Compass, UserCheck, HeartPulse, RefreshCw, Info, User, Building2,
  ShieldCheck, DollarSign, PackageCheck, FlaskConical, TrendingUp,
  FileCheck, RotateCcw
} from 'lucide-react';

export interface OrionApp {
  id: string;
  name: string;
  route: string;
  category: 'Operations' | 'Intelligence' | 'Control' | 'Platform' | 'AI';
  icon: any; // Lucide icon or OrionIcons string/component
  color: string;
  description: string;
  dockDefault?: boolean;
}

export const ORION_REGISTRY: Record<string, OrionApp> = {
  'command-center': {
    id: 'command-center',
    name: 'Command Center',
    route: '/',
    category: 'Operations',
    icon: LayoutDashboard,
    color: '#00F2FE',
    description: 'Central supply chain observability and command workspace.',
    dockDefault: true,
  },
  'inventory': {
    id: 'inventory',
    name: 'Inventory',
    route: '/inventory',
    category: 'Operations',
    icon: Package,
    color: '#10B981', // green
    description: 'Global inventory positioning and stock health.',
    dockDefault: true,
  },
  'procurement': {
    id: 'procurement',
    name: 'Procurement',
    route: '/procurement',
    category: 'Operations',
    icon: Target,
    color: '#F59E0B', // amber
    description: 'Purchase orders and material requisitions.',
    dockDefault: true,
  },
  'suppliers': {
    id: 'suppliers',
    name: 'Suppliers',
    route: '/suppliers',
    category: 'Operations',
    icon: Users,
    color: '#3B82F6', // blue
    description: 'Supplier health, performance, and communication.',
    dockDefault: true,
  },
  'shipments': {
    id: 'shipments',
    name: 'Shipments',
    route: '/shipments',
    category: 'Operations',
    icon: Truck,
    color: '#F97316', // orange
    description: 'Inbound and outbound logistics tracking.',
    dockDefault: true,
  },
  'exceptions': {
    id: 'exceptions',
    name: 'Exceptions',
    route: '/exceptions',
    category: 'Control',
    icon: AlertTriangle,
    color: '#EF4444', // red
    description: 'Supply chain disruptions and risk alerts.',
    dockDefault: true,
  },
  'approval-center': {
    id: 'approval-center',
    name: 'Approval Center',
    route: '/approvals',
    category: 'Control',
    icon: ShieldCheck,
    color: '#00F2FE',
    description: 'Centralized human-in-the-loop governance for AI recommendations, quality holds, and high-value orders.',
    dockDefault: true,
  },
  'master-data': {
    id: 'master-data',
    name: 'Data & Integration Fabric',
    route: '/master-data',
    category: 'Platform',
    icon: Database,
    color: '#6366F1',
    description: 'Master Data Lifecycle, ERP Integration Contracts, State Reconciliation, and Event Fabric Replay.',
    dockDefault: false,
  },
  'quality': {
    id: 'quality',
    name: 'Quality Center',
    route: '/quality',
    category: 'Operations',
    icon: ShieldCheck,
    color: '#F43F5E',
    description: 'AQL lot inspection, defect quarantine, Non-Conformance Reports (NCR), and hold releases.',
    dockDefault: false,
  },
  'invoice-matching': {
    id: 'invoice-matching',
    name: 'Invoice 3-Way Match',
    route: '/invoice-matching',
    category: 'Operations',
    icon: DollarSign,
    color: '#10B981',
    description: 'Automated 3-way cross-referencing (PO vs GRN vs Invoice) and variance approval.',
    dockDefault: false,
  },
  'gate-receiving': {
    id: 'gate-receiving',
    name: 'Gate & GRN Center',
    route: '/gate-receiving',
    category: 'Operations',
    icon: PackageCheck,
    color: '#3B82F6',
    description: 'Physical carrier gate check-in, dock door allocation, and Goods Receipt Note (GRN) posting.',
    dockDefault: false,
  },
  'vendor-onboarding': {
    id: 'vendor-onboarding',
    name: 'Vendor Onboarding & RFQ',
    route: '/vendor-onboarding',
    category: 'Control',
    icon: Users,
    color: '#F59E0B',
    description: 'Supplier self-service onboarding, ESG vetting, compliance audit, and multi-criteria RFQ awards.',
    dockDefault: false,
  },
  'world-model': {
    id: 'world-model',
    name: 'World Model',
    route: '/world-model',
    category: 'Intelligence',
    icon: Globe,
    color: '#06B6D4', // cyan
    description: '3D Digital Twin and network ontology.',
    dockDefault: true,
  },
  'orion-ai': {
    id: 'orion-ai',
    name: 'ORION AI',
    route: '/copilot',
    category: 'AI',
    icon: Brain,
    color: '#8B5CF6', // violet
    description: 'Native generative intelligence and reasoning.',
    dockDefault: false,
  },
  'reports': {
    id: 'reports',
    name: 'Reports',
    route: '/reports',
    category: 'Platform',
    icon: FileText,
    color: '#6366F1', // indigo
    description: 'Analytical reports and document generation.',
    dockDefault: true,
  },
  'documents': {
    id: 'documents',
    name: 'Document Workspace',
    route: '/documents',
    category: 'Platform',
    icon: FileText,
    color: '#818CF8',
    description: 'Tamper-evident document repository, OCR parsing, classification, and entity binding.',
    dockDefault: true,
  },
  'user-manual': {
    id: 'user-manual',
    name: 'ORION-9 User Manual',
    route: '/manual',
    category: 'Platform',
    icon: HelpCircle,
    color: '#22D3EE',
    description: 'Complete guide to using ORION OS, applications, AI, workflows, and settings.',
    dockDefault: false,
  },
  'settings': {
    id: 'settings',
    name: 'Settings',
    route: '/settings',
    category: 'Platform',
    icon: Settings,
    color: '#64748B', // neutral
    description: 'System settings, user preferences, and configuration.',
    dockDefault: true,
  },
  // --- Extended Operations ---
  'inbound': {
    id: 'inbound',
    name: 'Inbound',
    route: '/inbound',
    category: 'Operations',
    icon: Truck, // or a specific icon
    color: '#F97316',
    description: 'Inbound logistics and receiving.',
  },
  'outbound': {
    id: 'outbound',
    name: 'Outbound',
    route: '/outbound',
    category: 'Operations',
    icon: Truck,
    color: '#F97316',
    description: 'Outbound fulfillment and shipping.',
  },
  'warehouse': {
    id: 'warehouse',
    name: 'Warehouse',
    route: '/warehouse',
    category: 'Operations',
    icon: Database,
    color: '#10B981',
    description: 'Warehouse optimization and slotting.',
  },
  // --- Extended Intelligence ---
  'predictions': {
    id: 'predictions',
    name: 'Predictions',
    route: '/predictions',
    category: 'Intelligence',
    icon: Activity,
    color: '#8B5CF6',
    description: 'ML forecasts and lead time predictions.',
  },
  'demand-forecasting': {
    id: 'demand-forecasting',
    name: 'Demand',
    route: '/demand-forecasting',
    category: 'Intelligence',
    icon: BarChart2,
    color: '#8B5CF6',
    description: 'Demand sensing and forecasting.',
  },
  'inventory-optimization': {
    id: 'inventory-optimization',
    name: 'Inv Intelligence',
    route: '/inventory-optimization',
    category: 'Intelligence',
    icon: Package,
    color: '#10B981',
    description: 'Multi-echelon inventory optimization.',
  },
  'scenarios': {
    id: 'scenarios',
    name: 'Scenarios',
    route: '/scenarios',
    category: 'Intelligence',
    icon: Network,
    color: '#0ea5e9',
    description: 'What-if scenario planning and simulation.',
  },
  'digital-twin': {
    id: 'digital-twin',
    name: 'Digital Twin',
    route: '/digital-twin',
    category: 'Intelligence',
    icon: Globe,
    color: '#06B6D4',
    description: 'System digital twin overview.',
  },
  'risk-radar': {
    id: 'risk-radar',
    name: 'Risk Radar',
    route: '/risk-radar',
    category: 'Intelligence',
    icon: AlertTriangle,
    color: '#ef4444',
    description: 'Proactive risk identification.',
  },
  // --- Extended Control ---
  'decisions': {
    id: 'decisions',
    name: 'Decision Center',
    route: '/decisions',
    category: 'Control',
    icon: Zap,
    color: '#f59e0b',
    description: 'Automated decision reviews.',
  },
  'action-center': {
    id: 'action-center',
    name: 'Action Center',
    route: '/action-center',
    category: 'Control',
    icon: Target,
    color: '#f59e0b',
    description: 'Pending workflow actions.',
  },
  'autopilot': {
    id: 'autopilot',
    name: 'Autopilot',
    route: '/autopilot',
    category: 'Control',
    icon: Brain,
    color: '#8B5CF6',
    description: 'Autonomous control policies.',
  },
  'workflows': {
    id: 'workflows',
    name: 'Workflows',
    route: '/workflows',
    category: 'Control',
    icon: Network,
    color: '#0ea5e9',
    description: 'Workflow builder and orchestration.',
  },
  // --- Deep Intelligence (Memory, Agents, Signals) ---
  'memory': {
    id: 'memory',
    name: 'ORION Memory',
    route: '/memory',
    category: 'AI',
    icon: Brain,
    color: '#8B5CF6',
    description: 'Vector knowledge and context memory.',
  },
  'intelligence-center': {
    id: 'intelligence-center',
    name: 'Deep Intelligence',
    route: '/intelligence-center',
    category: 'AI',
    icon: Activity,
    color: '#8B5CF6',
    description: 'Advanced intelligence capabilities.',
  },
  'signal-language': {
    id: 'signal-language',
    name: 'Signal Language',
    route: '/signal-language',
    category: 'AI',
    icon: Activity,
    color: '#8B5CF6',
    description: 'Real-time telemetry streams.',
  },
  'network-intelligence': {
    id: 'network-intelligence',
    name: 'Network Intel',
    route: '/network-intelligence',
    category: 'AI',
    icon: Network,
    color: '#8B5CF6',
    description: 'Network topology and intelligence.',
  },
  'decision-science': {
    id: 'decision-science',
    name: 'Decision Science',
    route: '/decision-science',
    category: 'AI',
    icon: Zap,
    color: '#8B5CF6',
    description: 'Causal reasoning and decisions.',
  },
  // --- Platform / Data ---
  'data': {
    id: 'data',
    name: 'Data Center',
    route: '/data',
    category: 'Platform',
    icon: Database,
    color: '#0ea5e9',
    description: 'Data ingestion and lakes.',
  },
  'data-quality': {
    id: 'data-quality',
    name: 'Data Quality',
    route: '/data-quality',
    category: 'Platform',
    icon: Activity,
    color: '#10B981',
    description: 'Telemetry and data quality metrics.',
  },
  'integrations': {
    id: 'integrations',
    name: 'Integrations',
    route: '/integrations',
    category: 'Platform',
    icon: Link,
    color: '#6366f1',
    description: 'External system connectors.',
  },
  'observability': {
    id: 'observability',
    name: 'Observability',
    route: '/observability',
    category: 'Platform',
    icon: Activity,
    color: '#3b82f6',
    description: 'System observability and metrics.',
  },
  // --- Finance/Other ---
  'cost-optimizer': {
    id: 'cost-optimizer',
    name: 'Cost Optimizer',
    route: '/cost-optimizer',
    category: 'Operations',
    icon: BarChart2,
    color: '#10b981',
    description: 'Supply chain cost analytics.',
  },
  'working-capital': {
    id: 'working-capital',
    name: 'Working Capital',
    route: '/working-capital',
    category: 'Operations',
    icon: BarChart2,
    color: '#10b981',
    description: 'Working capital and cashflow.',
  },
  'contracts': {
    id: 'contracts',
    name: 'Contracts',
    route: '/contracts',
    category: 'Operations',
    icon: FileText,
    color: '#6366f1',
    description: 'Supplier contract intelligence.',
  },
  'supplier-comms': {
    id: 'supplier-comms',
    name: 'Communications',
    route: '/supplier-comms',
    category: 'Operations',
    icon: Users,
    color: '#3b82f6',
    description: 'Supplier collaboration.',
  },
  'logistics': {
    id: 'logistics',
    name: 'Logistics',
    route: '/logistics',
    category: 'Operations',
    icon: Map,
    color: '#f97316',
    description: 'Transportation and logistics planning.',
  },
  'event-fabric': {
    id: 'event-fabric',
    name: 'Event Fabric',
    route: '/event-fabric',
    category: 'Intelligence',
    icon: Activity,
    color: '#00F2FE',
    description: 'Real-time supply chain event streaming fabric.',
  },
  'autonomy-center': {
    id: 'autonomy-center',
    name: 'Autonomy Center',
    route: '/autonomy-center',
    category: 'Control',
    icon: Zap,
    color: '#8B5CF6',
    description: 'Supervised and fully autonomous operational controls.',
  },
  'causal-intelligence': {
    id: 'causal-intelligence',
    name: 'Causal Engine',
    route: '/causal-intelligence',
    category: 'Intelligence',
    icon: GitBranch,
    color: '#06B6D4',
    description: 'Root-cause attribution and directed causal modeling.',
  },
  'counterfactual': {
    id: 'counterfactual',
    name: 'Counterfactual',
    route: '/counterfactual',
    category: 'Intelligence',
    icon: Compass,
    color: '#3B82F6',
    description: 'Exploration of alternate operational realities.',
  },
  'decision-economics': {
    id: 'decision-economics',
    name: 'Economics',
    route: '/decision-economics',
    category: 'Intelligence',
    icon: BarChart2,
    color: '#10B981',
    description: 'Financial payoffs and decision cost-benefit modeling.',
  },
  'attention-center': {
    id: 'attention-center',
    name: 'Attention Center',
    route: '/attention-center',
    category: 'Control',
    icon: Eye,
    color: '#F59E0B',
    description: 'Prioritized operational signals requiring human focus.',
  },
  'information-gaps': {
    id: 'information-gaps',
    name: 'Information Gaps',
    route: '/information-gaps',
    category: 'Intelligence',
    icon: HelpCircle,
    color: '#EC4899',
    description: 'Missing telemetry, uncertainties, and blindspot detection.',
  },
  'constraints': {
    id: 'constraints',
    name: 'Constraints',
    route: '/constraints',
    category: 'Control',
    icon: Sliders,
    color: '#6366F1',
    description: 'Network operational boundaries and capacity constraints.',
  },
  'policies': {
    id: 'policies',
    name: 'Policies',
    route: '/policies',
    category: 'Control',
    icon: FileText,
    color: '#3B82F6',
    description: 'Configurable decision boundaries and execution rules.',
  },
  'outcomes': {
    id: 'outcomes',
    name: 'Outcomes',
    route: '/outcomes',
    category: 'Intelligence',
    icon: Target,
    color: '#10B981',
    description: 'Historical decision outcome tracking and accuracy.',
  },
  'decision-replay': {
    id: 'decision-replay',
    name: 'Decision Replay',
    route: '/decision-replay',
    category: 'Intelligence',
    icon: History,
    color: '#8B5CF6',
    description: 'Step-by-step playback of past automated decisions.',
  },
  'time-machine': {
    id: 'time-machine',
    name: 'Time Machine',
    route: '/time-machine',
    category: 'Intelligence',
    icon: Clock,
    color: '#00F2FE',
    description: 'Historical state inspection and temporal replay.',
  },
  'decision-dna': {
    id: 'decision-dna',
    name: 'Decision DNA',
    route: '/decision-dna',
    category: 'Intelligence',
    icon: GitBranch,
    color: '#6366F1',
    description: 'Evolutionary history of decision policies and heuristics.',
  },
  'human-ai': {
    id: 'human-ai',
    name: 'Human-AI Teaming',
    route: '/human-ai',
    category: 'Intelligence',
    icon: UserCheck,
    color: '#F59E0B',
    description: 'Cooperative oversight, trust metrics, and delegation.',
  },
  'vital-signs': {
    id: 'vital-signs',
    name: 'Vital Signs',
    route: '/vital-signs',
    category: 'Operations',
    icon: HeartPulse,
    color: '#EF4444',
    description: 'Core operational pulses, throughputs, and system health.',
  },
  'quiet-risk': {
    id: 'quiet-risk',
    name: 'Quiet Risk',
    route: '/quiet-risk',
    category: 'Intelligence',
    icon: ShieldAlert,
    color: '#F97316',
    description: 'Sub-threshold systemic risks and latent vulnerabilities.',
  },
  'sync': {
    id: 'sync',
    name: 'Sync Monitor',
    route: '/sync',
    category: 'Platform',
    icon: RefreshCw,
    color: '#06B6D4',
    description: 'Live ERP, WMS, and TMS synchronization state.',
  },
  'about': {
    id: 'about',
    name: 'About ORION',
    route: '/about',
    category: 'Platform',
    icon: Info,
    color: '#00F2FE',
    description: 'Operating environment version, build, and architecture.',
  },
  'time-world': {
    id: 'time-world',
    name: 'Time & World',
    route: '/time-world',
    category: 'Platform',
    icon: Globe2,
    color: '#00D9FF',
    description: 'Global time zones, live time, and interactive world clock.',
  },
  'profile': {
    id: 'profile',
    name: 'User Profile',
    route: '/profile',
    category: 'Platform',
    icon: User,
    color: '#3B82F6',
    description: 'Operator credentials, role, and preferences.',
  },
  'organization': {
    id: 'organization',
    name: 'Organization',
    route: '/organization',
    category: 'Platform',
    icon: Building2,
    color: '#8B5CF6',
    description: 'Enterprise organization profile and domain settings.',
  },
  'control-center': {
    id: 'control-center',
    name: 'Control Center',
    route: '/control-center',
    category: 'Control',
    icon: ShieldCheck,
    color: '#00F2FE',
    description: 'System control center and advanced simulations.',
  },
  'platform-intelligence': {
    id: 'platform-intelligence',
    name: 'Platform Intelligence',
    route: '/platform-intelligence',
    category: 'Platform',
    icon: Brain,
    color: '#8B5CF6',
    description: 'Platform AI settings and models.',
  },
  'workflow-builder': {
    id: 'workflow-builder',
    name: 'Workflow Builder',
    route: '/workflow-builder',
    category: 'Control',
    icon: GitBranch,
    color: '#06B6D4',
    description: 'Visual workflow orchestration, version immutability, and simulation.',
    dockDefault: true,
  },
  'workflow-monitor': {
    id: 'workflow-monitor',
    name: 'Workflow Monitor',
    route: '/workflow-monitor',
    category: 'Intelligence',
    icon: Activity,
    color: '#10B981',
    description: 'Live instance trace spans, execution timelines, and failure analysis.',
    dockDefault: true,
  },
  'digital-twin-center': {
    id: 'digital-twin-center',
    name: 'Digital Twin Center',
    route: '/digital-twin-center',
    category: 'Intelligence',
    icon: Network,
    color: '#06B6D4',
    description: 'Enterprise multi-relational supply chain topology and state reconciliation.',
    dockDefault: true,
  },
  'scenario-lab': {
    id: 'scenario-lab',
    name: 'Scenario Lab',
    route: '/scenario-lab',
    category: 'Intelligence',
    icon: FlaskConical,
    color: '#A855F7',
    description: 'Deterministic what-if scenario simulations and multi-scenario trade-off analysis.',
    dockDefault: true,
  },
  'scenario-result': {
    id: 'scenario-result',
    name: 'Scenario Results',
    route: '/scenario-result',
    category: 'Intelligence',
    icon: TrendingUp,
    color: '#EC4899',
    description: 'Analytical impact inspector, risk contagion paths, and Wave 7 workflow bridge.',
    dockDefault: false,
  },
  'outcome-center': {
    id: 'outcome-center',
    name: 'Outcome Center',
    route: '/admin/outcomes',
    category: 'Control',
    icon: FileCheck,
    color: '#10B981',
    description: 'Closed-loop expected vs actual telemetry, variance calculation, and decision effectiveness.',
    dockDefault: true,
  },
  'learning-center': {
    id: 'learning-center',
    name: 'Learning Center',
    route: '/admin/learning',
    category: 'Intelligence',
    icon: Brain,
    color: '#6366F1',
    description: 'Systemic learning signals, governed improvement proposals, and versioned releases.',
    dockDefault: true,
  },
  'drift-center': {
    id: 'drift-center',
    name: 'Drift Center',
    route: '/admin/drift',
    category: 'Intelligence',
    icon: Compass,
    color: '#3B82F6',
    description: 'Continuous concept and data drift monitoring across operational variables.',
    dockDefault: false,
  },
  'rollback-center': {
    id: 'rollback-center',
    name: 'Rollback Center',
    route: '/admin/rollback',
    category: 'Control',
    icon: RotateCcw,
    color: '#F59E0B',
    description: 'Governed configuration version ledger and 1-click rollback engine.',
    dockDefault: false,
  },
  'production-readiness': {
    id: 'production-readiness',
    name: 'Production Readiness',
    route: '/admin/readiness',
    category: 'Platform',
    icon: ShieldCheck,
    color: '#10B981',
    description: 'Production control plane for security gates, latencies, and zero-regression health.',
    dockDefault: false,
  },
};
