import React, { useMemo, useState } from 'react';
import { Check, ChevronRight, CircleHelp, Lock, Play, Search, Sparkles, SlidersHorizontal, UserCog, ShieldCheck, Workflow, Database, PlugZap, Bell, BarChart3, Globe2, Factory, Truck, ShoppingCart, Boxes, FileText, Smartphone, Server, BrainCircuit, Users, Building2, KeyRound } from 'lucide-react';
import { useAuth } from '../../store/AuthContext';
import { useToast } from '../../store/ToastContext';

 type Mode = 'manual' | 'copilot' | 'autopilot';
 type Domain = { id:string; name:string; icon:React.ElementType; priority:'P0'|'P1'|'P2'|'P3'; description:string; features:string[] };

 const domains:Domain[] = [
  {id:'identity',name:'Identity, Users & Access',icon:Users,priority:'P0',description:'Users, RBAC, tenancy, identity providers, MFA, sessions, API keys and immutable audit.',features:['User account lifecycle','Custom roles & permission matrix','Multi-tenancy & tenant isolation','SSO / SAML / OAuth / OIDC / LDAP','MFA / 2FA policies','Session timeout & forced logout','API keys, scopes & rate limits','Audit trail & retention']},
  {id:'security',name:'Security & Compliance',icon:ShieldCheck,priority:'P0',description:'Security posture, privacy, compliance, backup and recovery controls.',features:['Encryption & key management','Compliance frameworks','Retention & right-to-be-forgotten','IP allowlist & geo controls','Security headers / CORS / CSRF','SAST / DAST / vulnerability scans','Backup, restore & disaster recovery','Consent & DPA management']},
  {id:'configuration',name:'Platform Configuration',icon:SlidersHorizontal,priority:'P0',description:'Turn modules on/off, manage feature flags, workflows, business rules, statuses and calendars.',features:['Module enable / disable','Feature flags & rollout rings','Visual workflow & approval engine','Business rules engine','Numbering & sequencing','Status / state machine','Notifications & escalation','Calendars, shifts & holidays']},
  {id:'master-data',name:'Master Data',icon:Database,priority:'P0',description:'Govern the core entities used by every supply-chain process.',features:['Item / SKU master','Supplier / vendor master','Customer master','Location / facility hierarchy','Carrier / 3PL master','Bill of Materials','Currency & exchange rates','Tax configuration','Units of measure','Country / region / trade zones']},
  {id:'procurement',name:'Procurement & Sourcing',icon:ShoppingCart,priority:'P0',description:'Configure purchasing policies, approvals, matching, sourcing and supplier risk.',features:['Purchasing policies','Approval matrix','Three-way match tolerances','Supplier portal configuration','Contracts & agreements','RFQ / RFx sourcing rules','Supplier risk & compliance']},
  {id:'inventory',name:'Inventory & Warehouse',icon:Boxes,priority:'P0',description:'Configure inventory ownership, valuation, traceability, replenishment and warehouse execution.',features:['Multi-location setup','Inventory valuation','Stock status & segregation','Batch / lot / serial tracking','Reorder & replenishment rules','Cycle count & physical inventory','Barcode / RFID / QR','Zones, slots & pick paths','Inter-location transfers']},
  {id:'orders',name:'Order Management',icon:FileText,priority:'P0',description:'Control order types, routing, pricing, promotions, returns, backorders and channels.',features:['Order types & field visibility','Fulfillment routing','Pricing & discount engine','Promotions & campaigns','Returns / RMA','Backorder management','Multi-channel consolidation']},
  {id:'logistics',name:'Transportation & Logistics',icon:Truck,priority:'P1',description:'Manage carriers, lanes, freight, docks, POD, fleet, customs and shipment milestones.',features:['Carrier management','Routes & lanes','Freight cost rules','Dock scheduling','Proof of delivery','Fleet / vehicle management','Customs & trade compliance','Container & shipment tracking']},
  {id:'manufacturing',name:'Manufacturing & Production',icon:Factory,priority:'P1',description:'Configure production orders, routing, capacity, quality, shop floor and maintenance.',features:['Production order setup','Routing & operations','Capacity planning','Quality management','Shop floor control','Maintenance & assets']},
  {id:'demand',name:'Demand Planning & Forecasting',icon:BarChart3,priority:'P1',description:'Manage forecasts, demand sensing, S&OP, accuracy and collaboration.',features:['Forecasting models','Demand sensing','S&OP cycles','Forecast accuracy','Collaborative planning']},
  {id:'analytics',name:'Analytics & Reporting',icon:BarChart3,priority:'P0',description:'Govern KPIs, report builders, executive reports, data exports and anomaly alerts.',features:['Role-based KPI dashboards','Supply-chain KPI library','Custom report builder','Executive / MIS reports','Data warehouse & lake exports','Anomaly detection & alerting']},
  {id:'integrations',name:'Integration & API Management',icon:PlugZap,priority:'P1',description:'Central control plane for ERP, EDI, APIs, events, IoT, mappings and third-party services.',features:['API gateway & versioning','ERP / commerce / TMS / WMS connectors','EDI X12 / EDIFACT','Event bus & webhooks','IoT / telematics','Data mapping & synchronization','Third-party service connectors']},
  {id:'documents',name:'Documents & E-Signature',icon:FileText,priority:'P1',description:'Templates, automatic generation, signatures, archive and regulatory documents.',features:['Document templates','Automatic document generation','E-signature providers','Document archive & indexing','Regulatory documents']},
  {id:'global',name:'Global & Regional Operations',icon:Globe2,priority:'P1',description:'Localization, multi-entity, regional compliance, trade screening and sustainability.',features:['Localization & languages','Multi-currency / legal entities','Regional compliance packs','Sanctions & trade screening','Carbon / sustainability tracking','UTC storage & local display']},
  {id:'operations',name:'System Operations',icon:Server,priority:'P0',description:'Environment, health, releases, migrations, performance, logs, sandbox and licensing.',features:['Environment management','System health & monitoring','Release management & rollback','Data migration / import / export','Caching & performance','Logging & debugging','Sandbox / test mode','License & subscription management']},
  {id:'ai',name:'AI / ML Governance',icon:BrainCircuit,priority:'P2',description:'Control AI forecasting, prediction, optimization, copilot, digital twin and RPA with human approval.',features:['AI demand forecasting','Predictive analytics','Prescriptive optimization','ORION Copilot','Traceability / blockchain','Digital twin scenarios','RPA & bot orchestration']},
  {id:'portals',name:'Customer & Partner Portals',icon:Building2,priority:'P2',description:'Configure supplier, customer, carrier and distributor portals with isolated access.',features:['Supplier portal','Customer portal','Carrier / 3PL portal','Partner / distributor portal','Portal access control & branding']},
  {id:'mobile',name:'Mobile & Field',icon:Smartphone,priority:'P2',description:'Manage mobile releases, offline synchronization, devices and push notifications.',features:['Mobile app management','Offline mode & conflict resolution','Field device management','Push notifications']},
 ];

 const priorityStyles:Record<string,string>={P0:'text-red-400 bg-red-500/10 border-red-500/20',P1:'text-amber-400 bg-amber-500/10 border-amber-500/20',P2:'text-cyan-400 bg-cyan-500/10 border-cyan-500/20',P3:'text-os-text-muted bg-os-surface border-os-border'};

 export const AdminControlCenter=()=>{
  const { currentUser }=useAuth(); const {showToast}=useToast();
  const [active,setActive]=useState('identity'); const [query,setQuery]=useState(''); const [mode,setMode]=useState<Mode>('manual'); const [aiEnabled,setAiEnabled]=useState(true); const [selected,setSelected]=useState<string|null>(null);
  const storageKey=`orion-admin-control:${currentUser?.id||'admin'}`;
  const [enabled,setEnabled]=useState<Record<string,boolean>>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return {}}});
  const domain=domains.find(d=>d.id===active)||domains[0];
  const filtered=useMemo(()=>domains.filter(d=>`${d.name} ${d.description} ${d.features.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query]);
  const toggle=(key:string)=>{const next={...enabled,[key]:enabled[key]===false};setEnabled(next);localStorage.setItem(storageKey,JSON.stringify(next));showToast(`${key} ${next[key]?'enabled':'disabled'} in control policy`,'success');};
  const aiApply=()=>{if(!aiEnabled){showToast('AI governance is disabled','error');return;} showToast('AI proposal generated. Review and approve each change before execution.','success');};
  return <div className="w-full min-w-0 space-y-5 animate-in fade-in duration-300">
   <header className="flex flex-col xl:flex-row xl:items-end justify-between gap-4">
    <div><div className="flex items-center gap-2 mb-2"><span className="text-[10px] font-mono tracking-[0.25em] text-cyan-400 uppercase">ADMIN CONTROL PLANE</span><span className="px-1.5 py-0.5 rounded border border-blue-500/20 bg-blue-500/10 text-blue-300 text-[9px]">SYSTEMATIC</span></div><h1 className="text-3xl font-light tracking-tight text-os-text-primary">Platform Configuration Center</h1><p className="text-sm text-os-text-secondary mt-1 max-w-3xl">One control plane for manual administration and governed AI automation. Every change is scoped, reviewable and designed to leave an audit trail.</p></div>
    <div className="flex gap-2"><button onClick={aiApply} className="inline-flex items-center gap-2 px-3 py-2 rounded-md bg-blue-600 hover:bg-blue-500 text-white text-xs font-medium"><Sparkles size={14}/> AI Configuration Review</button><button onClick={()=>showToast('Policy validation completed','success')} className="inline-flex items-center gap-2 px-3 py-2 rounded-md border border-os-border bg-os-surface hover:bg-os-surface-hover text-xs"><Check size={14}/> Validate Policies</button></div>
   </header>

   <section className="grid grid-cols-1 lg:grid-cols-4 gap-3">
    {[['18','Domains'],['~100','Capabilities'],['P0','Build First'],[aiEnabled?'AI READY':'AI OFF','Governance']].map(([v,l],i)=><div key={l} className="rounded-lg border border-os-border bg-os-bg p-4"><div className="text-xl text-os-text-primary font-light">{v}</div><div className="text-[10px] uppercase tracking-widest text-os-text-muted mt-1">{l}</div></div>)}
   </section>

   <section className="rounded-lg border border-blue-900/40 bg-blue-950/15 p-4 flex flex-col xl:flex-row gap-4 xl:items-center justify-between">
    <div className="flex items-start gap-3"><div className="p-2 rounded-lg bg-blue-500/10 text-blue-300"><BrainCircuit size={18}/></div><div><div className="text-sm font-medium text-os-text-primary">AI Governance</div><div className="text-xs text-os-text-secondary mt-1">AI may inspect, recommend and prepare changes. High-impact actions remain approval-gated.</div></div></div>
    <div className="flex flex-wrap items-center gap-2"><button onClick={()=>setAiEnabled(!aiEnabled)} className={`px-3 py-1.5 rounded border text-[10px] uppercase tracking-widest ${aiEnabled?'border-cyan-500/30 bg-cyan-500/10 text-cyan-300':'border-os-border bg-os-surface text-os-text-muted'}`}>{aiEnabled?'AI ENABLED':'AI DISABLED'}</button><div className="flex border border-os-border rounded-md overflow-hidden"><button onClick={()=>setMode('manual')} className={`px-3 py-1.5 text-[10px] ${mode==='manual'?'bg-os-surface-active text-os-text-primary':'text-os-text-muted'}`}>MANUAL</button><button onClick={()=>setMode('copilot')} className={`px-3 py-1.5 text-[10px] ${mode==='copilot'?'bg-os-surface-active text-os-text-primary':'text-os-text-muted'}`}>COPILOT</button><button onClick={()=>setMode('autopilot')} className={`px-3 py-1.5 text-[10px] ${mode==='autopilot'?'bg-os-surface-active text-os-text-primary':'text-os-text-muted'}`}>AUTOPILOT</button></div></div>
   </section>

   <div className="grid grid-cols-1 xl:grid-cols-[300px_minmax(0,1fr)] gap-5 min-h-[650px]">
    <aside className="rounded-lg border border-os-border bg-os-bg overflow-hidden flex flex-col"><div className="p-3 border-b border-os-border"><div className="relative"><Search size={14} className="absolute left-3 top-2.5 text-os-text-muted"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search capabilities..." className="w-full bg-os-surface border border-os-border rounded-md pl-9 pr-3 py-2 text-xs text-os-text-primary outline-none"/></div></div><div className="p-2 overflow-y-auto">{filtered.map(d=>{const I=d.icon;return <button key={d.id} onClick={()=>{setActive(d.id);setSelected(null)}} className={`w-full text-left flex items-center gap-3 p-3 rounded-md mb-1 ${active===d.id?'bg-blue-500/10 text-blue-300 border border-blue-900/30':'hover:bg-os-surface text-os-text-secondary border border-transparent'}`}><I size={16}/><div className="min-w-0 flex-1"><div className="text-xs font-medium truncate">{d.name}</div><div className="text-[9px] text-os-text-muted mt-0.5">{d.features.length} capabilities</div></div><span className={`px-1.5 py-0.5 rounded border text-[8px] ${priorityStyles[d.priority]}`}>{d.priority}</span></button>})}</div></aside>

    <main className="rounded-lg border border-os-border bg-os-bg overflow-hidden">
      <div className="p-5 border-b border-os-border flex flex-col lg:flex-row lg:items-center justify-between gap-4"><div className="flex items-start gap-3"><div className="p-2.5 rounded-lg bg-os-surface border border-os-border"><domain.icon size={20}/></div><div><h2 className="text-lg font-medium text-os-text-primary">{domain.name}</h2><p className="text-xs text-os-text-secondary mt-1 max-w-2xl">{domain.description}</p></div></div><div className={`px-2 py-1 rounded border text-[9px] font-mono ${priorityStyles[domain.priority]}`}>{domain.priority} PRIORITY</div></div>
      <div className="p-4 grid grid-cols-1 2xl:grid-cols-2 gap-3">{domain.features.map((feature,idx)=>{const key=`${domain.id}.${feature}`;const on=enabled[key]!==false;const isSelected=selected===key;return <div key={key} className={`rounded-lg border ${isSelected?'border-blue-500/40':'border-os-border'} bg-os-surface p-4`}><div className="flex items-start justify-between gap-3"><button className="text-left flex-1" onClick={()=>setSelected(isSelected?null:key)}><div className="text-sm text-os-text-primary font-medium">{feature}</div><div className="text-[10px] text-os-text-muted mt-1">Policy scope · {mode} · audit required</div></button><button onClick={()=>toggle(key)} className={`relative w-10 h-5 rounded-full shrink-0 ${on?'bg-cyan-500/40':'bg-os-surface-active'}`}><span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white transition-transform ${on?'translate-x-5':'translate-x-0.5'}`}/></button></div>{isSelected&&<div className="mt-4 pt-3 border-t border-os-border grid grid-cols-1 md:grid-cols-3 gap-2"><div className="p-3 rounded bg-os-bg border border-os-border"><div className="text-[9px] uppercase tracking-widest text-os-text-muted">Manual</div><div className="text-xs mt-1 text-os-text-secondary">Admin configures policy, scope and exceptions.</div></div><div className="p-3 rounded bg-os-bg border border-os-border"><div className="text-[9px] uppercase tracking-widest text-cyan-400">AI Copilot</div><div className="text-xs mt-1 text-os-text-secondary">AI analyzes current state and proposes changes for approval.</div></div><div className="p-3 rounded bg-os-bg border border-os-border"><div className="text-[9px] uppercase tracking-widest text-purple-400">Autopilot</div><div className="text-xs mt-1 text-os-text-secondary">Only enabled after explicit policy, scope and approval thresholds are defined.</div></div><button onClick={()=>showToast(`${feature}: configuration workspace opened`,'success')} className="md:col-span-3 inline-flex items-center justify-center gap-2 px-3 py-2 rounded border border-os-border hover:bg-os-surface-hover text-xs"><SlidersHorizontal size={13}/> Open Configuration Workspace <ChevronRight size={13}/></button></div>}</div>})}</div>
    </main>
   </div>

   <section className="rounded-lg border border-os-border bg-os-bg p-5"><div className="flex items-center gap-2 mb-4"><Lock size={15} className="text-cyan-400"/><h3 className="text-sm font-semibold uppercase tracking-widest text-os-text-primary">Governance Rules</h3></div><div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-4 gap-3">{[['Least privilege','Permissions default to deny.'],['Human approval','High-impact AI actions require approval.'],['Tenant isolation','Configuration scope is explicit per tenant.'],['Audit first','Policy changes record actor, time and before/after state.']].map(([a,b])=><div key={a} className="p-3 rounded border border-os-border bg-os-surface"><div className="text-xs font-medium text-os-text-primary">{a}</div><div className="text-[10px] text-os-text-muted mt-1">{b}</div></div>)}</div></section>
  </div>
 }
