/**
 * ORION-9 AUTHORITATIVE METRIC DEFINITION REGISTRY
 * 
 * Defines all governed enterprise metrics across 17+ SCM operational domains.
 * Enforces strict metadata typing, tenant/environment scoping, units, and data sources.
 */

export type MetricDomain =
  | 'procurement'
  | 'inventory'
  | 'planning'
  | 'demand'
  | 'manufacturing'
  | 'quality'
  | 'logistics'
  | 'orders'
  | 'finance'
  | 'risk'
  | 'sustainability'
  | 'control_tower'
  | 'ai'
  | 'workflow';

export type MetricAggregationType = 'sum' | 'avg' | 'count' | 'latest' | 'rate' | 'ratio';

export type MetricDataSource = 
  | 'firestore/inventory'
  | 'firestore/purchase_orders'
  | 'firestore/shipments'
  | 'firestore/customer_orders'
  | 'firestore/invoices'
  | 'firestore/suppliers'
  | 'firestore/exceptions'
  | 'firestore/quality_inspections'
  | 'firestore/production_orders'
  | 'firestore/metric_snapshots'
  | 'event_fabric'
  | 'integration/sap'
  | 'integration/oracle'
  | 'integration/edi'
  | 'demo_synthetic_engine';

export interface MetricDefinition {
  metricId: string;
  name: string;
  domain: MetricDomain;
  description: string;
  unit: string;
  aggregation: MetricAggregationType;
  source: MetricDataSource;
  tenantScoped: boolean;
  environmentScoped: boolean;
  timeSeriesSupported: boolean;
  liveSupported: boolean;
}

export const ENTERPRISE_METRIC_DEFINITIONS: Record<string, MetricDefinition> = {
  // 1. PROCUREMENT & SPEND
  SUPPLIER_OTIF: {
    metricId: 'SUPPLIER_OTIF',
    name: 'Supplier On-Time In-Full (OTIF)',
    domain: 'procurement',
    description: 'Percentage of purchase order line items delivered on time and in full',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/suppliers',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SUPPLIER_QUALITY: {
    metricId: 'SUPPLIER_QUALITY',
    name: 'Supplier Quality Rating',
    domain: 'procurement',
    description: 'Average quality score across active supplier deliveries',
    unit: '/100',
    aggregation: 'avg',
    source: 'firestore/quality_inspections',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  PO_CYCLE_TIME: {
    metricId: 'PO_CYCLE_TIME',
    name: 'PO Lead / Cycle Time',
    domain: 'procurement',
    description: 'Average days elapsed from purchase order creation to delivery',
    unit: 'days',
    aggregation: 'avg',
    source: 'firestore/purchase_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  PO_SPEND: {
    metricId: 'PO_SPEND',
    name: 'Total Committed PO Spend',
    domain: 'procurement',
    description: 'Sum of all active and confirmed purchase order commitment values',
    unit: 'USD',
    aggregation: 'sum',
    source: 'firestore/purchase_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 2. INVENTORY HEALTH
  INVENTORY_ON_HAND: {
    metricId: 'INVENTORY_ON_HAND',
    name: 'Inventory On Hand',
    domain: 'inventory',
    description: 'Total physical units currently stored across all warehouses',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  INVENTORY_VALUE: {
    metricId: 'INVENTORY_VALUE',
    name: 'Total Inventory Valuation',
    domain: 'inventory',
    description: 'Total financial valuation of on-hand inventory (units × unit cost)',
    unit: 'USD',
    aggregation: 'sum',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  INVENTORY_TURNS: {
    metricId: 'INVENTORY_TURNS',
    name: 'Inventory Turns (Annualized)',
    domain: 'inventory',
    description: 'Annualized rate at which inventory is sold and replaced',
    unit: 'turns/yr',
    aggregation: 'ratio',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  STOCKOUT_RATE: {
    metricId: 'STOCKOUT_RATE',
    name: 'Stockout Risk Count',
    domain: 'inventory',
    description: 'Number of SKUs currently below their safety stock threshold',
    unit: 'SKUs',
    aggregation: 'count',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SAFETY_STOCK: {
    metricId: 'SAFETY_STOCK',
    name: 'Total Safety Stock Buffer',
    domain: 'inventory',
    description: 'Sum of configured safety stock buffer quantities across all SKUs',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 3. ATP & ORDER PROMISING
  ATP_AVAILABLE: {
    metricId: 'ATP_AVAILABLE',
    name: 'Available-to-Promise (ATP) Inventory',
    domain: 'planning',
    description: 'Uncommitted physical and planned inventory available for new customer orders',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  ATP_SHORTAGE: {
    metricId: 'ATP_SHORTAGE',
    name: 'ATP Projected Shortages',
    domain: 'planning',
    description: 'Number of order lines facing ATP stock allocation deficits',
    unit: 'lines',
    aggregation: 'count',
    source: 'firestore/customer_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 4. DEMAND & S&OP
  DEMAND_FORECAST: {
    metricId: 'DEMAND_FORECAST',
    name: 'Projected Demand (30 Days)',
    domain: 'demand',
    description: 'AI statistical forecast for consumer and wholesale demand over 30 days',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  FORECAST_ACCURACY: {
    metricId: 'FORECAST_ACCURACY',
    name: 'Forecast Accuracy (MAPE Complement)',
    domain: 'demand',
    description: 'Statistical accuracy of demand forecast vs actual consumption',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/metric_snapshots',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SOP_DEMAND: {
    metricId: 'SOP_DEMAND',
    name: 'S&OP Unconstrained Demand',
    domain: 'planning',
    description: 'Consolidated commercial demand plan across all channels',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/customer_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SOP_SUPPLY: {
    metricId: 'SOP_SUPPLY',
    name: 'S&OP Constrained Supply Capacity',
    domain: 'planning',
    description: 'Aggregate production and procurement capacity committed to demand',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/purchase_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  MRP_SHORTAGE: {
    metricId: 'MRP_SHORTAGE',
    name: 'MRP Net Material Shortages',
    domain: 'planning',
    description: 'Critical bill-of-materials component shortages identified by MRP',
    unit: 'components',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 5. MANUFACTURING & QUALITY
  PRODUCTION_OUTPUT: {
    metricId: 'PRODUCTION_OUTPUT',
    name: 'Manufacturing Output Volume',
    domain: 'manufacturing',
    description: 'Total completed manufactured units during current operating window',
    unit: 'units',
    aggregation: 'sum',
    source: 'firestore/production_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  PRODUCTION_QUALITY: {
    metricId: 'PRODUCTION_QUALITY',
    name: 'First Pass Yield (FPY)',
    domain: 'quality',
    description: 'Percentage of manufactured products meeting QA standards on first inspection',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/quality_inspections',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 6. LOGISTICS & TRANSPORTATION
  ASN_VOLUME: {
    metricId: 'ASN_VOLUME',
    name: 'Advance Shipping Notices (ASN)',
    domain: 'logistics',
    description: 'Count of active inbound ASNs in pre-arrival/dock staging',
    unit: 'ASNs',
    aggregation: 'count',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SHIPMENT_VOLUME: {
    metricId: 'SHIPMENT_VOLUME',
    name: 'Active In-Transit Shipments',
    domain: 'logistics',
    description: 'Total active shipments currently moving in the global logistics network',
    unit: 'shipments',
    aggregation: 'count',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SHIPMENT_OTIF: {
    metricId: 'SHIPMENT_OTIF',
    name: 'Logistics Delivery OTIF',
    domain: 'logistics',
    description: 'Percentage of carrier shipments delivered on schedule without exceptions',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  TRANSIT_TIME: {
    metricId: 'TRANSIT_TIME',
    name: 'Average Transit Duration',
    domain: 'logistics',
    description: 'Average days elapsed between carrier departure and destination arrival',
    unit: 'days',
    aggregation: 'avg',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  DELIVERY_OTIF: {
    metricId: 'DELIVERY_OTIF',
    name: 'Final-Mile Delivery OTIF',
    domain: 'logistics',
    description: 'Customer delivery precision rate on final destination drop-offs',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  POD_COMPLETION: {
    metricId: 'POD_COMPLETION',
    name: 'Proof of Delivery (POD) Rate',
    domain: 'logistics',
    description: 'Percentage of delivered consignments with verified electronic POD sign-off',
    unit: '%',
    aggregation: 'rate',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 7. CUSTOMER ORDERS & FULFILLMENT
  ORDER_FILL_RATE: {
    metricId: 'ORDER_FILL_RATE',
    name: 'Order Fill Rate',
    domain: 'orders',
    description: 'Percentage of customer order lines fulfilled on initial ship attempt',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/customer_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  ORDER_CYCLE_TIME: {
    metricId: 'ORDER_CYCLE_TIME',
    name: 'Order-to-Delivery Cycle Time',
    domain: 'orders',
    description: 'Average hours elapsed from customer order placement to dispatch',
    unit: 'hours',
    aggregation: 'avg',
    source: 'firestore/customer_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  CUSTOMER_BACKORDERS: {
    metricId: 'CUSTOMER_BACKORDERS',
    name: 'Unfulfilled Backorders',
    domain: 'orders',
    description: 'Number of open customer orders delayed due to inventory unavailability',
    unit: 'orders',
    aggregation: 'count',
    source: 'firestore/customer_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 8. FINANCE & WORKING CAPITAL
  AR_OUTSTANDING: {
    metricId: 'AR_OUTSTANDING',
    name: 'Accounts Receivable (AR) Outstanding',
    domain: 'finance',
    description: 'Total pending customer receivables awaiting payment collection',
    unit: 'USD',
    aggregation: 'sum',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  AR_AGING: {
    metricId: 'AR_AGING',
    name: 'AR Aging > 60 Days',
    domain: 'finance',
    description: 'Receivables past 60 days overdue',
    unit: 'USD',
    aggregation: 'sum',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  AP_OUTSTANDING: {
    metricId: 'AP_OUTSTANDING',
    name: 'Accounts Payable (AP) Outstanding',
    domain: 'finance',
    description: 'Total pending supplier invoices committed for settlement',
    unit: 'USD',
    aggregation: 'sum',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  AP_AGING: {
    metricId: 'AP_AGING',
    name: 'AP Aging > 60 Days',
    domain: 'finance',
    description: 'Payables past 60 days of invoice receipt',
    unit: 'USD',
    aggregation: 'sum',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  WORKING_CAPITAL: {
    metricId: 'WORKING_CAPITAL',
    name: 'Net Working Capital Committed',
    domain: 'finance',
    description: 'Net operating capital tied up in inventory and receivables less payables',
    unit: 'USD',
    aggregation: 'latest',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  DIO: {
    metricId: 'DIO',
    name: 'Days Inventory Outstanding (DIO)',
    domain: 'finance',
    description: 'Average days inventory takes to turn into sales',
    unit: 'days',
    aggregation: 'latest',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  DSO: {
    metricId: 'DSO',
    name: 'Days Sales Outstanding (DSO)',
    domain: 'finance',
    description: 'Average days required to collect payment after sales invoice creation',
    unit: 'days',
    aggregation: 'latest',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  DPO: {
    metricId: 'DPO',
    name: 'Days Payable Outstanding (DPO)',
    domain: 'finance',
    description: 'Average days company takes to pay supplier trade invoices',
    unit: 'days',
    aggregation: 'latest',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  CASH_CONVERSION_CYCLE: {
    metricId: 'CASH_CONVERSION_CYCLE',
    name: 'Cash Conversion Cycle (CCC)',
    domain: 'finance',
    description: 'Operating metric representing days from cash outlay to cash inflow (DIO + DSO - DPO)',
    unit: 'days',
    aggregation: 'latest',
    source: 'firestore/invoices',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 9. REVERSE LOGISTICS & CUSTOMS
  RETURN_RATE: {
    metricId: 'RETURN_RATE',
    name: 'Customer Return Rate (RMA)',
    domain: 'orders',
    description: 'Percentage of delivered customer units returned under RMA',
    unit: '%',
    aggregation: 'rate',
    source: 'firestore/customer_orders',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  WARRANTY_CLAIMS: {
    metricId: 'WARRANTY_CLAIMS',
    name: 'Active Warranty Claims',
    domain: 'quality',
    description: 'Volume of unresolved warranty & defect claims undergoing triage',
    unit: 'claims',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  CUSTOMS_HOLDS: {
    metricId: 'CUSTOMS_HOLDS',
    name: 'Active Customs Holds',
    domain: 'logistics',
    description: 'International consignments held in border customs clearance',
    unit: 'holds',
    aggregation: 'count',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },

  // 10. RISK & CONTROL TOWER
  SUPPLIER_RISK: {
    metricId: 'SUPPLIER_RISK',
    name: 'Suppliers at High / Critical Risk',
    domain: 'risk',
    description: 'Count of active tier-1 and tier-2 suppliers evaluated as high/critical risk',
    unit: 'suppliers',
    aggregation: 'count',
    source: 'firestore/suppliers',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  NETWORK_UTILIZATION: {
    metricId: 'NETWORK_UTILIZATION',
    name: 'Supply Chain Network Utilization',
    domain: 'control_tower',
    description: 'Composite operational utilization rate across nodes and freight routes',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  WAREHOUSE_UTILIZATION: {
    metricId: 'WAREHOUSE_UTILIZATION',
    name: 'Average Warehouse Capacity Utilization',
    domain: 'inventory',
    description: 'Average physical rack and bay utilization across network distribution centers',
    unit: '%',
    aggregation: 'avg',
    source: 'firestore/inventory',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  CARRIER_PERFORMANCE: {
    metricId: 'CARRIER_PERFORMANCE',
    name: 'Carrier SLA Compliance',
    domain: 'logistics',
    description: 'Aggregate SLA conformance score across active logistics freight carriers',
    unit: '/100',
    aggregation: 'avg',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  SUSTAINABILITY_EMISSIONS: {
    metricId: 'SUSTAINABILITY_EMISSIONS',
    name: 'Carbon Emissions Index (Scope 1/3)',
    domain: 'sustainability',
    description: 'Calculated metric tons of CO2 equivalent for network transport & warehousing',
    unit: 'tCO2e',
    aggregation: 'sum',
    source: 'firestore/shipments',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  CONTROL_TOWER_EXCEPTIONS: {
    metricId: 'CONTROL_TOWER_EXCEPTIONS',
    name: 'Active Control Tower Exceptions',
    domain: 'control_tower',
    description: 'Total unresolved supply chain operational exceptions',
    unit: 'exceptions',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  CRITICAL_RISKS: {
    metricId: 'CRITICAL_RISKS',
    name: 'Critical / High Severity Disruptions',
    domain: 'control_tower',
    description: 'Disruptions requiring immediate human or autonomous intervention',
    unit: 'risks',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  AI_RECOMMENDATIONS: {
    metricId: 'AI_RECOMMENDATIONS',
    name: 'Autonomous AI Recommendations',
    domain: 'ai',
    description: 'Active proposed AI decision playbooks ready for human or automated approval',
    unit: 'actions',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  AI_ACTIONS: {
    metricId: 'AI_ACTIONS',
    name: 'Autonomous Decisions Executed',
    domain: 'ai',
    description: 'Automated remediation actions enacted by the Orion Autonomous Kernel',
    unit: 'executions',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
  WORKFLOW_BACKLOG: {
    metricId: 'WORKFLOW_BACKLOG',
    name: 'Pending Approval Tasks',
    domain: 'workflow',
    description: 'Human approval requests currently queued in the Governance Workbench',
    unit: 'tasks',
    aggregation: 'count',
    source: 'firestore/exceptions',
    tenantScoped: true,
    environmentScoped: true,
    timeSeriesSupported: true,
    liveSupported: true,
  },
};

export class MetricDefinitionRegistry {
  public static get(metricId: string): MetricDefinition | undefined {
    return ENTERPRISE_METRIC_DEFINITIONS[metricId];
  }

  public static getAll(): MetricDefinition[] {
    return Object.values(ENTERPRISE_METRIC_DEFINITIONS);
  }

  public static getByDomain(domain: MetricDomain): MetricDefinition[] {
    return Object.values(ENTERPRISE_METRIC_DEFINITIONS).filter(m => m.domain === domain);
  }

  public static isValid(metricId: string): boolean {
    return !!ENTERPRISE_METRIC_DEFINITIONS[metricId];
  }
}
