/**
 * ORION-9 WAVE 8: ENTERPRISE DIGITAL TWIN + SCENARIO INTELLIGENCE + SIMULATION
 * Temporal State Engine
 * 
 * Enforces strict architectural separation across three temporal planes:
 * 1. CURRENT_STATE: Real-time reconciled operational state
 * 2. HISTORICAL_STATE: Frozen retrospective snapshots
 * 3. PROJECTED_STATE: Hypothetical future states generated by simulations
 * 
 * Guarantees zero cross-contamination: simulations can never write to CURRENT_STATE.
 */

import { TemporalStateMode, TwinSnapshot, TwinEntity } from './types';
import { TwinGraphEngine } from './TwinGraphEngine';

export class TemporalStateEngine {
  private static instance: TemporalStateEngine;
  private currentGraphs: Map<string, TwinGraphEngine> = new Map(); // key: tenantId
  private historicalSnapshots: Map<string, TwinSnapshot> = new Map(); // key: `${tenantId}:${snapshotId}`
  private projectedSnapshots: Map<string, TwinSnapshot> = new Map(); // key: `${tenantId}:${simulationId}`
  private stateEntities: Map<string, TwinEntity[]> = new Map(); // key: `${tenantId}:${mode}:${contextId || 'default'}`

  private constructor() {}

  public static getInstance(): TemporalStateEngine {
    if (!TemporalStateEngine.instance) {
      TemporalStateEngine.instance = new TemporalStateEngine();
    }
    return TemporalStateEngine.instance;
  }

  public saveState(
    tenantId: string,
    mode: TemporalStateMode,
    entities: TwinEntity[],
    contextId: string = 'default'
  ): void {
    const key = `${tenantId}:${mode}:${contextId}`;
    this.stateEntities.set(key, JSON.parse(JSON.stringify(entities)));
  }

  public getState(
    tenantId: string,
    mode: TemporalStateMode,
    contextId: string = 'default'
  ): TwinEntity[] {
    const key = `${tenantId}:${mode}:${contextId}`;
    const entities = this.stateEntities.get(key) || [];
    return JSON.parse(JSON.stringify(entities));
  }

  public setCurrentState(tenantId: string, graph: TwinGraphEngine): void {
    this.currentGraphs.set(tenantId, graph);
  }

  public getCurrentState(tenantId: string): TwinGraphEngine | undefined {
    return this.currentGraphs.get(tenantId);
  }

  public registerHistoricalSnapshot(snapshot: TwinSnapshot): void {
    this.historicalSnapshots.set(`${snapshot.tenantId}:${snapshot.snapshotId}`, JSON.parse(JSON.stringify(snapshot)));
  }

  public getHistoricalSnapshot(tenantId: string, snapshotId: string): TwinSnapshot | undefined {
    const snp = this.historicalSnapshots.get(`${tenantId}:${snapshotId}`);
    return snp ? JSON.parse(JSON.stringify(snp)) : undefined;
  }

  public registerProjectedSnapshot(simulationId: string, snapshot: TwinSnapshot): void {
    this.projectedSnapshots.set(`${snapshot.tenantId}:${simulationId}`, JSON.parse(JSON.stringify(snapshot)));
  }

  public getProjectedSnapshot(tenantId: string, simulationId: string): TwinSnapshot | undefined {
    const snp = this.projectedSnapshots.get(`${tenantId}:${simulationId}`);
    return snp ? JSON.parse(JSON.stringify(snp)) : undefined;
  }

  /**
   * Asserts that a simulated state cannot mutate current production state
   */
  public assertStateIsolation(targetMode: TemporalStateMode, isSimulation: boolean): void {
    if (isSimulation && targetMode === 'CURRENT_STATE') {
      throw new Error('Temporal Violation: Scenario simulation is strictly forbidden from writing to CURRENT_STATE');
    }
  }

  public clear(): void {
    this.currentGraphs.clear();
    this.historicalSnapshots.clear();
    this.projectedSnapshots.clear();
    this.stateEntities.clear();
  }
}

export const temporalStateEngine = TemporalStateEngine.getInstance();
